### Question 1. 
#### Given the 3-dimensional coordinates of two points, please design a script to compute the distance between the two points in 3-dimensional coordinate system.

In [6]:
x1 = input("Please enter the value of x1: ")  # Point 1
y1 = input("Please enter the value of y1: ")
z1 = input("Please enter the value of z1: ")

x2 = input("Please enter the value of x2: ")  # Point 2
y2 = input("Please enter the value of y2: ")
z2 = input("Please enter the value of z2: ")

In [7]:
import math as m
XS = (int(x2)-int(x1))**2
YS = (int(y2)-int(y1))**2
ZS = (int(z2)-int(z1))**2
result = m.sqrt(XS+YS+ZS)
print(result)

5.196152422706632


### Question 2. 
#### Please design a script to compute the value of the following determinant.
$$
\left|\begin{array}{ccc} 
a & b & c\\
d & e & f\\
g & h & i
\end{array}\right|
$$ 

In [14]:
import numpy as np
mtx = np.zeros(dtype=int, shape=(3,3))
for i in range (3):
    for j in range (3):
        inpt = int(input("please enter a value:"))
        mtx[i][j]=inpt
print (f"your matrix is: \n {mtx}")
aei = mtx[0][0] * mtx[1][1] * mtx[2][2]
bfg = mtx[0][1] * mtx[1][2] * mtx[2][0]
cdh = mtx[0][2] * mtx[1][0] * mtx[2][1]
ceg = mtx[0][2] * mtx[1][1] * mtx[2][0]
bdi = mtx[0][1] * mtx[1][0] * mtx[2][2]
afh = mtx[0][0] * mtx[1][2] * mtx[2][1]
determinan = (aei + bfg + cdh) - (ceg + bdi + afh)
print (f"T matrix : {determinan}")


your matrix is: 
 [[15 20 25]
 [16 18 20]
 [ 3  9 12]]
T matrix : 150


### Question 3. 
#### Given a number in range (1000, 10000), could you design a script to compute the cubic sum of each bit? (e.g. 1324 ----> 1+27+8+64 = 100)

In [19]:
val = input("please enter a number between 1000 and 10000 :")
if (1000<int(val)<10000):
    sumation = 0
    for indx in val:
        sumation += (int(indx)**3)
else:
    print("you didn't enter a valid number")  

print (sumation)

100
