### Question 1. 
#### Given 3 integers x, y, z (any value you like), please design a script to pass the value of x to z, value of y to x, value of z to y.

In [3]:
x = 1
y = 2
z = 3

# Enter your code here

print(f"x={x}, y={y}, z={z}")

x=1, y=2, z=3


In [4]:
x,y,z = 1,2,3

x,y,z = y,z,x

print(f"x={x}, y={y}, z={z}")

x=2, y=3, z=1


### Question 2. 
#### Please design a script to compute the result of the following matrix multiplication.
$$
\left[\begin{array}{ccc} 
a & b \\
c & d \\
e & f 
\end{array}\right]
\left[\begin{array}{cc} 
g & h & i \\
j & k & l \\
\end{array}\right]
$$ 

In [3]:
import numpy as np
#1
mtx_1 = np.zeros(dtype=int, shape=(3,2))
for i in range (3):
    for j in range (2):
        inpt = int(input("please enter a value:"))
        mtx_1[i][j]=inpt
print (f"your first matrix is: \n {mtx_1}")
#2
mtx_2 = np.zeros(dtype=int, shape=(2,3))
for i in range (2):
    for j in range (3):
        inpt_2 = int(input("please enter a value:"))
        mtx_2[i][j]=inpt_2
print (f"your second matrix is: \n {mtx_2}")

mtx_res = np.zeros(dtype=int, shape=(3,3))

mtx_res[0][0] = (mtx_1[0][0]*mtx_2[0][0])+(mtx_1[0][1]*mtx_2[1][0]) 
mtx_res[0][1] = (mtx_1[0][0]*mtx_2[0][1])+(mtx_1[0][1]*mtx_2[1][1]) 
mtx_res[0][2] = (mtx_1[0][0]*mtx_2[0][2])+(mtx_1[0][1]*mtx_2[1][2]) 
mtx_res[1][0] = (mtx_1[1][0]*mtx_2[0][0])+(mtx_1[1][1]*mtx_2[1][0]) 
mtx_res[1][1] = (mtx_1[1][0]*mtx_2[0][1])+(mtx_1[1][1]*mtx_2[1][1]) 
mtx_res[1][2] = (mtx_1[1][0]*mtx_2[0][2])+(mtx_1[1][1]*mtx_2[1][2]) 
mtx_res[2][0] = (mtx_1[2][0]*mtx_2[0][0])+(mtx_1[2][1]*mtx_2[1][0]) 
mtx_res[2][1] = (mtx_1[2][0]*mtx_2[0][1])+(mtx_1[2][1]*mtx_2[1][1]) 
mtx_res[2][2] = (mtx_1[2][0]*mtx_2[0][2])+(mtx_1[2][1]*mtx_2[1][2]) 

print(f"the value of the multiplication is : \n {mtx_res}")


your first matrix is: 
 [[1 2]
 [3 4]
 [5 6]]
your second matrix is: 
 [[1 2 3]
 [4 5 6]]
the value of the multiplication is : 
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]
